In [1]:
import numpy as np

In [2]:
data = [15, 16, 18, 19, 22, 24, 29, 30, 34]

In [3]:
print('Mean: ', np.mean(data))
print('Median: ', np.median(data))
print('50th percentile: ', np.percentile(data, 50))
print('25th percentile: ', np.percentile(data, 25))
print('75 percentile: ', np.percentile(data, 75))
print('Variance: ', np.var(data))
print('Standard deviation: ', np.std(data))

Mean:  23.0
Median:  22.0
50th percentile:  22.0
25th percentile:  18.0
75 percentile:  29.0
Variance:  40.22222222222222
Standard deviation:  6.342099196813483


# Numpy is a Python package for manipulating lists and tables of numerical data. We can use it to do a lot of statistical calculations. We call the list or table of data a numpy array.

We often will take the data from our pandas DataFrame and put it in numpy arrays. Pandas DataFrames are great because we have the column names and other text data that makes it human readable. A DataFrame, while easy for a human to read, is not the ideal format for doing calculations. The numpy arrays are generally less human readable, but are in a format that enables the necessary computation.

We often start with our data in a Pandas DataFrame, but then want to convert it to a numpy array. The values attribute does this for us.

Let's convert the Fare column to a numpy array.

In [5]:
import pandas as pd

# read_csv function takes a file in csv format and converts it to a Pandas DataFrame
df = pd.read_csv('https://sololearn.com/uploads/files/titanic.csv')

In [6]:
# The result is a 1-dimension array. why? Only one square bracket
df['Fare'].values

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
        41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,  21.6792,
        17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,  61.9792,
        35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,   7.2292,
        80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,  10.5   ,
         8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,  73.5   ,
        14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,  29.    ,
        12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,  10.5   ,
        15.85  ,  34.375 ,   8.05  , 263.    ,   8.05  ,   8.0

The values attribute of a Pandas Series give the data as a numpy array.

If we have a pandas DataFrame (instead of a Series as in the last part), we can still use the values attribute, but it returns a 2-dimensional numpy array.

In [9]:
small_df = df[['Pclass', 'Fare', 'Age', 'Survived']]
arr = small_df.values

This is a 2-dimensional numpy array. You can tell because there’s two sets of brackets, and it expands both across the page and down

We use numpy shape attribute to determine the size of our numpy array

In [10]:
print(arr.shape)

(887, 4)


If we look at the shape, we get the number of rows and the number of columns

You can also use the shape attribute on a pandas DataFrame (df.shape)

In [11]:
df.shape

(887, 7)

In [14]:
df.head()
print(arr)

[[ 3.      7.25   22.      0.    ]
 [ 1.     71.2833 38.      1.    ]
 [ 3.      7.925  26.      1.    ]
 ...
 [ 3.     23.45    7.      0.    ]
 [ 1.     30.     26.      1.    ]
 [ 3.      7.75   32.      0.    ]]


In [22]:
# select a single element from a numpy array with the following
arr[884, 3]

0.0

In [23]:
# select a single row, for example, the whole row of the first passenger
arr[0]

array([ 3.  ,  7.25, 22.  ,  0.  ])

In [24]:
# To select a single column (in this case the Age column), we have to use some special syntax
arr[:,2]

array([22.  , 38.  , 26.  , 35.  , 35.  , 27.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 23.  ,
       31.  , 22.  , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  , 26.  ,
       19.  , 24.  , 23.  , 40.  , 48.  , 18.  , 66.  , 28.  , 42.  ,
       18.  , 21.  , 18.  , 14.  , 40.  , 27.  ,  3.  , 19.  , 30.  ,
       20.  , 27.  , 16.  , 18.  ,  7.  , 21.  , 49.  , 29.  , 65.  ,
       46.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,  4.  ,
       64.  ,  7.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  , 21.  ,
       26.  , 32.  , 25.  , 23.  , 28.  ,  0.83, 30.  , 22.  , 29.  ,
       31.  , 28.  , 17.  , 33.  , 16.  , 20.  , 23.  , 24.  , 29.  ,
       20.  , 46.  , 26.  , 59.  , 22.  , 71.  , 23.  , 34.  , 34.  ,
       28.  , 29.  , 21.  , 33.  , 37.  , 28.  , 21.  , 29.  , 38.  ,
       28.  , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 , 29.  ,
       24.  ,  2.  , 21.  , 19.  , 32.5 , 32.5 , 54.  , 12.  , 19.  ,
       24.  ,  2.  ,

# Masking

In [25]:
# Often times you want to select all the rows that meet a certain criteria.
# select all the rows of children (passengers under the age of 18). 
mask = arr[:,2] < 18

A mask is a boolean array (True/False values) that tells us which values from the array we’re interested in

In [26]:
arr[mask]

array([[  3.    ,  21.075 ,   2.    ,   0.    ],
       [  2.    ,  30.0708,  14.    ,   1.    ],
       [  3.    ,  16.7   ,   4.    ,   1.    ],
       [  3.    ,   7.8542,  14.    ,   0.    ],
       [  3.    ,  29.125 ,   2.    ,   0.    ],
       [  3.    ,   8.0292,  15.    ,   1.    ],
       [  3.    ,  21.075 ,   8.    ,   0.    ],
       [  3.    ,  11.2417,  14.    ,   1.    ],
       [  2.    ,  41.5792,   3.    ,   1.    ],
       [  3.    ,  21.6792,  16.    ,   0.    ],
       [  3.    ,  39.6875,   7.    ,   0.    ],
       [  2.    ,  27.75  ,   5.    ,   1.    ],
       [  3.    ,  46.9   ,  11.    ,   0.    ],
       [  3.    ,  27.9   ,   4.    ,   0.    ],
       [  3.    ,  15.2458,   7.    ,   1.    ],
       [  3.    ,   7.925 ,  17.    ,   1.    ],
       [  3.    ,  46.9   ,  16.    ,   0.    ],
       [  2.    ,  29.    ,   0.83  ,   1.    ],
       [  2.    ,  10.5   ,  17.    ,   1.    ],
       [  3.    ,  34.375 ,  16.    ,   0.    ],
       [  3.    ,  1

# Summing and Counting 

Let’s say we want to know how many of our passengers are children. We still have the same array definition and can take our mask or boolean values from the previous part.

Recall that True values are interpreted as 1 and False values are interpreted as 0. So we can just sum up the array and that’s equivalent to counting the number of true values.

In [27]:
print(mask.sum())

130


Summing an array of boolean values gives the count of the number of True values